### ISSUE TITLE
Libafl uses a fork because of rand

### ISSUE THREAD

**Issue by comcma** [landaire/lain#1]
I'm not sure if this is still an issue, but  Libafl use this fork in their tutorial: https://github.com/AFLplusplus/LibAFL/blob/eac7307c5af0dbcbacd2bee66bd5534b97924071/fuzzers/tutorial/Cargo.toml#L26. Might be worth upstreaming those changes, and PR'ing to fix the libafl tutorial documentation.

**Comment by landaire** [comment]
Fixed in https://github.com/landaire/lain/commit/0fb4a5b74876f51b42a57bc1f327a5ac260c27e2
